# NVDA Add-on Manifest
# Amélioration de l'accessibilité de ProtonVPN

name = protonVPNAccessibility
summary = Amélioration de l'accessibilité de ProtonVPN
description = Améliore l'accessibilité de l'application ProtonVPN pour Windows avec NVDA.
version = 1.0.0
author = Mama Sene <tech.access33@gmail.com>
url = https://github.com/mamasene/add-on_protonvpn
docFileName = readme.html
minimumNVDAVersion = 2025.1
lastTestedNVDAVersion = 2026.1
updateChannel = stable
