# NVDA Add-on Manifest
# ProtonVPN Accessibility

name = protonVPNAccessibility
summary = ProtonVPN Accessibility
description = Improves accessibility of the ProtonVPN Windows application for NVDA users.
version = 1.0.1
author = Mama Sene <tech.access33@gmail.com>
url = https://github.com/mamasene/add-on_protonvpn-o
docFileName = readme.html
minimumNVDAVersion = 2025.1
lastTestedNVDAVersion = 2026.1
updateChannel = stable